# Generated by Django 4.2.5 on 2023-12-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zurita_Tomas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrito',
            old_name='fechainscripcion',
            new_name='fecha_inscripcion',
        ),
        migrations.RenameField(
            model_name='inscrito',
            old_name='horainscripcion',
            new_name='hora_inscripcion',
        ),
    ]
