# Generated by Django 4.2.5 on 2023-12-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zurita_Tomas_app', '0002_rename_fechainscripcion_inscrito_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrito',
            old_name='fecha_inscripcion',
            new_name='fechainscripcion',
        ),
        migrations.RenameField(
            model_name='inscrito',
            old_name='hora_inscripcion',
            new_name='horainscripcion',
        ),
    ]
